apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ing-feature
spec:
  ingressClassName: nginx
  rules:
  - host: {{ ING_ADDRESS }}
    http:
      paths:
      - backend:
          service:
            name: webapp-svc
            port:
              number: 8080
        path: /
        pathType: Prefix
