apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-test
spec:
  ingressClassName: nginx
  rules:
  - host: java-webapp-test-argocd.example.com
    http:
      paths:
      - backend:
          service:
            name: webapp-svc
            port:
              number: 8080
        path: /
        pathType: Prefix
