kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv00001
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/data-volume/